[run]
init_cmds = [
	["go", "run", "main.go"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = [
    "$WORKDIR/assets",
    "$WORKDIR/controllers",
    "$WORKDIR/models",
    "$WORKDIR/views",
]						            # Directories to watch
watch_exts = [".go",".html",".css",".js",".jpg",".jpeg",".png"]	# Extensions to watch
ignore = [".git", "vendor"] 	    # Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 500					# Minimal interval to Trigger build event
interrupt_timout = 5				# Time to wait until force kill
graceful_kill = true				# Wait for exit and before directly kill
cmds = [
    ["../../bin/go-bindata","-o","static/assets/assets.go","-pkg","assets","assets/..."],
    ["../../bin/go-bindata","-o","static/views/views.go","-pkg","views","views/..."],
	["go", "run", "main.go"]
]									# Commands to run